"""
Django settings for core project.

Generated by 'django-admin startproject' using Django 6.0.2.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

import os
from pathlib import Path
from dotenv import (
    load_dotenv,
)
from django.core.exceptions import ImproperlyConfigured

# Загрузка переменных окружения из .env файла
load_dotenv()

BASE_DIR = Path(__file__).resolve().parent.parent
load_dotenv(BASE_DIR / ".env")  # added path to .env

# 1. SECRET_KEY: строго из .env. Если нет → остановка с пояснением
SECRET_KEY = os.getenv("SECRET_KEY")
if not SECRET_KEY:
    raise ImproperlyConfigured(
        "SECRET_KEY не найден в .env или переменных окружения! "
        "Добавьте строку SECRET_KEY=ваш-ключ в backend/.env"
    )

# 2. DEBUG: Берем из .env (по умолчанию False для безопасности, но для разработки можно True)
DEBUG = os.getenv("DEBUG", "False").lower() in ("true", "1", "yes")

# 3. ALLOWED_HOSTS: Берем список из .env или используем localhost для разработки
ALLOWED_HOSTS_ENV = os.getenv("ALLOWED_HOSTS", "localhost,127.0.0.1")
ALLOWED_HOSTS = [host.strip() for host in ALLOWED_HOSTS_ENV.split(",")]


# Application definition

INSTALLED_APPS = [
    "jazzmin",
    # django own
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    # Сторонние приложения
    "rest_framework",
    "rest_framework_simplejwt",
    "corsheaders",
    # Локальные приложения
    "exercises",
    "core",
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "corsheaders.middleware.CorsMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "core.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [BASE_DIR / "templates"],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "core.wsgi.application"


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.postgresql",
        "NAME": os.environ.get("POSTGRES_DB", "german_db"),
        "USER": os.environ.get("POSTGRES_USER", "german_user"),
        "PASSWORD": os.environ.get("POSTGRES_PASSWORD", "german_password"),
        "HOST": os.environ.get("POSTGRES_HOST", "localhost"),
        "PORT": os.environ.get("POSTGRES_PORT", "5432"),
    }
}

# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = "static/"

# core/settings.py (в конец файла)

REST_FRAMEWORK = {
    "DEFAULT_AUTHENTICATION_CLASSES": (
        "rest_framework_simplejwt.authentication.JWTAuthentication",
    ),
    "DEFAULT_PERMISSION_CLASSES": (
        "rest_framework.permissions.IsAuthenticated",  # Или IsAuthenticatedOrReadOnly для начала
    ),
}

from datetime import timedelta

SIMPLE_JWT = {
    "ACCESS_TOKEN_LIFETIME": timedelta(minutes=60),
    "REFRESH_TOKEN_LIFETIME": timedelta(days=1),
    "ROTATE_REFRESH_TOKENS": True,
    "BLACKLIST_AFTER_ROTATION": True,
    "ALGORITHM": "HS256",
    "SIGNING_KEY": SECRET_KEY,
    "AUTH_HEADER_TYPES": ("Bearer",),
}

# Для CORS (чтобы фронтенд на Vue мог обращаться к бэкенду)

CORS_ALLOWED_ORIGINS = [
    "http://localhost:5173",  # Стандартный порт Vite для Vue 3
    "http://127.0.0.1:5173",
]


# Jazzmin

JAZZMIN_SETTINGS = {
    # Заголовок окна браузера
    "site_title": "German Exercises Admin",
    # Заголовок на экране входа и в углу админки
    "site_header": "German Exercises School",
    # Бренд в левом верхнем углу
    "site_brand": "Admin Panel",
    # Логотип (можно указать путь к картинке или URL)
    "site_logo": None,
    # Приветственное сообщение
    "welcome_sign": "Добро пожаловать, Виктор!",
    # Поиск по моделям (очень удобно!)
    "search_model": ["exercises.Exercise", "exercises.Student", "auth.User"],
    # Иконки для моделей (автоматически подбираются, но можно задать вручную)
    "icons": {
        "exercises.Exercise": "fas fa-book",
        "exercises.Topic": "fas fa-tags",
        "exercises.Student": "fas fa-user-graduate",
        "auth.User": "fas fa-user-shield",
    },
    # Порядок отображения приложений в меню
    "order_with_respect_to": [
        "exercises",
        "auth",
        "sites",
    ],
}


# Отключаем автоматическое добавление слэша в конце URL
# Это нужно для совместимости с фронтендом, который шлет запросы без слэша
APPEND_SLASH = False
