# Generated by Django 6.0.2 on 2026-03-03 12:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Exercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название упражнения')),
                ('exercise_type', models.CharField(choices=[('vocabulary_drill', 'Vocabulary Drill'), ('gap_fill', 'Gap Fill')], max_length=50, verbose_name='Тип')),
                ('language', models.CharField(default='german', max_length=20, verbose_name='Язык')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активно')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Упражнение',
                'verbose_name_plural': 'Упражнения',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Название темы')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Тема',
                'verbose_name_plural': 'Темы',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Sentence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='Текст предложения')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('exercise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sentences', to='exercises.exercise', verbose_name='Упражнение')),
            ],
            options={
                'verbose_name': 'Предложение',
                'verbose_name_plural': 'Предложения',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='GapOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('placeholder_index', models.PositiveIntegerField(verbose_name='Индекс пропуска')),
                ('options', models.JSONField(verbose_name='Варианты ответов')),
                ('correct_answer', models.CharField(max_length=100, verbose_name='Правильный ответ')),
                ('sentence', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gap_options', to='exercises.sentence', verbose_name='Предложение')),
            ],
            options={
                'verbose_name': 'Опция пропуска',
                'verbose_name_plural': 'Опции пропусков',
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50, verbose_name='Имя')),
                ('last_name', models.CharField(max_length=50, verbose_name='Фамилия')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Email')),
                ('level', models.CharField(choices=[('A1', 'A1'), ('A2', 'A2'), ('B1', 'B1'), ('B2', 'B2')], default='A1', max_length=10, verbose_name='Уровень')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='student_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Ученик',
                'verbose_name_plural': 'Ученики',
            },
        ),
        migrations.CreateModel(
            name='ExerciseResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField(default=0, verbose_name='Баллы')),
                ('total_questions', models.IntegerField(default=0, verbose_name='Всего вопросов')),
                ('completed_at', models.DateTimeField(auto_now_add=True)),
                ('details', models.JSONField(blank=True, default=dict, verbose_name='Детали ответа')),
                ('exercise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='exercises.exercise')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='exercises.student')),
            ],
            options={
                'verbose_name': 'Результат упражнения',
                'verbose_name_plural': 'Результаты упражнений',
                'ordering': ['-completed_at'],
            },
        ),
        migrations.AddField(
            model_name='exercise',
            name='topics',
            field=models.ManyToManyField(related_name='exercises', to='exercises.topic', verbose_name='Темы'),
        ),
        migrations.CreateModel(
            name='VocabularyCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=100, verbose_name='Слово (DE)')),
                ('correct_translation', models.CharField(max_length=100, verbose_name='Правильный перевод')),
                ('distractor_1', models.CharField(max_length=100, verbose_name='Дистрактор 1')),
                ('distractor_2', models.CharField(max_length=100, verbose_name='Дистрактор 2')),
                ('distractor_3', models.CharField(max_length=100, verbose_name='Дистрактор 3')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('exercise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vocabulary_cards', to='exercises.exercise', verbose_name='Упражнение')),
            ],
            options={
                'verbose_name': 'Карточка слова',
                'verbose_name_plural': 'Карточки слов',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='StudentTopicProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exercises_completed', models.IntegerField(default=0, verbose_name='Выполнено упражнений')),
                ('last_practiced', models.DateTimeField(auto_now=True, verbose_name='Последняя практика')),
                ('mastery_level', models.FloatField(default=0.0, verbose_name='Уровень освоения (0-1)')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='topic_progress', to='exercises.student')),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_progress', to='exercises.topic')),
            ],
            options={
                'verbose_name': 'Прогресс по теме',
                'verbose_name_plural': 'Прогресс по темам',
                'unique_together': {('student', 'topic')},
            },
        ),
    ]
